[RPGF-72] Add impact statement section
catalyzt-tech/RetroPGF-Hub pull request #41
Opened 2024-09-16 16:13 UTC by Billy19191

# Description

[//]: # "Please include a summary of the changes and the related issue. (You can write below without deleting this comment)"
Introducing impact metric of application to Retro Funding 5 from lastest data from Agora

### What
[//]: # "Briefly describe this feature / fix / refactor (You can write below without deleting this comment)"
In this PR, I introduce impact statement section to project details page fro Retro Funding 5 which contain claim statement of each project that request for funding.

### Why
[//]: # "Describe the reason why we need this feature / fix / refactor or refer to Jira Ticket (You can write below without deleting this comment)"
This is necessary info for everyone espectially for badgeholder to read, review their impact statement.

## Type of change

Please check the relevent option with `x`.

- [] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (if needed)
- [x] My changes generate no new warnings
- [x] I have tested on my `Local Machine`

2024-09-16 16:23 UTC, Billy19191 commented on app/lib/common.tsx
> +}
I think leaving it as it is fine, more readable, and maintained.

2024-09-16 16:28 UTC, Billy19191 commented on app/(white_navbar)/explore/RetroPGF5/[name]/_component/_Project/ImpactStatementSection.tsx
> +                  dangerouslySetInnerHTML={{
Thank for flagging this!

2024-09-17 07:18 UTC, wit03 commented
@Billy19191 Is the data source migrated from EAS to Agora already?

2024-09-17 07:22 UTC, wit03 requested changes

2024-09-17 07:22 UTC, wit03 commented on app/(white_navbar)/explore/RetroPGF5/_component/DynamicCard.tsx
> +    () => handleCategoryRound5(category, 'text-xs'),
Parsing `text-size` through handleCategory seems a bit off since we didn't do this for all last round. Are there any reason for this?

2024-09-17 07:42 UTC, wit03 approved these changes
LGTM (Resolved in Offline conversation)

2024-09-17 07:43 UTC, merged