[RPGF-79] Add Project / Application Status
catalyzt-tech/RetroPGF-Hub pull request #44
Opened 2024-10-01 13:12 UTC by Billy19191

# Description

[//]: # "Please include a summary of the changes and the related issue. (You can write below without deleting this comment)"
Add project / application status to all project Retro Funding 5

### What
[//]: # "Briefly describe this feature / fix / refactor (You can write below without deleting this comment)"
Enforce elgigbility in Retro Funding 5 card (all projects are eligible since Agora update their endpoint)

### Why
[//]: # "Describe the reason why we need this feature / fix / refactor or refer to Jira Ticket (You can write below without deleting this comment)"
To make it clear which project or application is qualify or diaqualify status for user to explore

## Type of change

Please check the relevent option with `x`.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (if needed)
- [x] My changes generate no new warnings
- [x] I have tested on my `Local Machine`

2024-10-01 13:15 UTC, Billy19191 commented
Note that, don't merge this PR until #43 is merged.

2024-10-02 04:02 UTC, wit03 commented
@Billy19191 Will review after #43 is merged.

2024-10-02 15:15 UTC, Billy19191 commented on app/(white_navbar)/explore/RetroPGF5/RetroType5.d.ts
> +  testimonials: string
Base on Agora API, this testimonial is string link not array. So, it's look good now!

2024-10-02 15:15 UTC, Billy19191 commented on app/(white_navbar)/explore/RetroPGF5/_component/Tab/ProjectTab.tsx
> +                    isEligible={true}
Since all projects has already filter from Agora side, so we can force all projects status as true

2024-10-02 15:15 UTC, Billy19191 commented on app/(white_navbar)/explore/RetroPGF5/RetroType5.d.ts
> +  investment: Investment[]
Leave it as it is fine, since there's no project that have VC from Agora API, so we don't know the type of it.

2024-10-03 09:35 UTC, wit03 commented
#43 is merged. some conflict need to be resolved

2024-10-03 20:00 UTC, wit03 requested changes

2024-10-03 20:13 UTC, wit03 approved these changes
LGTM

2024-10-03 20:13 UTC, merged